server:
   port: 8080
         
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/shop_bridge
      username: root
      password: root     
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
      